services:
  - type: web
    name: ieee-docs-evaluator-backend
    env: java
    rootDir: Backend/docs-evaluator
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/docs-evaluator-0.0.1-SNAPSHOT.jar
    healthCheckPath: /api/settings
